# Generated by Django 4.1.3 on 2022-11-14 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('ID_PRODUCT', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='id_products')),
                ('NAME_PRODUCT', models.CharField(max_length=49, verbose_name='name_products')),
                ('PRICE_PRODUCT', models.CharField(max_length=48, verbose_name='price_products')),
                ('IMG_PRODUCT', models.URLField(verbose_name='img_products')),
            ],
            options={
                'verbose_name': 'products',
                'verbose_name_plural': 'products',
            },
        ),
    ]
