# Generated by Django 4.1.3 on 2022-11-15 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home_content',
            fields=[
                ('ID_HOME', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='id_home')),
                ('PAGE_LINK_1', models.CharField(max_length=30, null=True, verbose_name='ssilka_na_stranichku_1')),
                ('PAGE_LINK_2', models.CharField(max_length=30, null=True, verbose_name='ssilka_na_stranichku_2')),
            ],
            options={
                'verbose_name': 'products',
                'verbose_name_plural': 'products',
            },
        ),
    ]
