# Generated by Django 4.1.3 on 2022-11-15 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_home_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='home_content',
            options={'verbose_name': 'content', 'verbose_name_plural': 'content'},
        ),
    ]
