# Generated by Django 4.1.3 on 2022-11-15 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_home_content_page_link_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home_content',
            name='PAGE_LINK_1',
            field=models.CharField(blank=True, max_length=30, verbose_name='ssilka_na_stranichku_1'),
        ),
        migrations.AlterField(
            model_name='home_content',
            name='PAGE_LINK_2',
            field=models.CharField(blank=True, max_length=30, verbose_name='ssilka_na_stranichku_2'),
        ),
    ]
