# Generated by Django 4.1.3 on 2022-11-18 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_home_content_page_link_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home_Slider',
            fields=[
                ('ID_H_SLIDER', models.CharField(max_length=1, primary_key=True, serialize=False, verbose_name='id_home_slider')),
                ('TEXT_1', models.CharField(blank=True, max_length=150, verbose_name='text 1')),
                ('TEXT_2', models.CharField(blank=True, max_length=150, verbose_name='text 2')),
                ('PAGE_LINK', models.CharField(blank=True, max_length=30, verbose_name='page_url')),
                ('IMG_SLIDER', models.URLField(verbose_name='img_slider')),
            ],
            options={
                'verbose_name': 'slider',
                'verbose_name_plural': 'slider',
            },
        ),
    ]
