# Generated by Django 4.1.2 on 2022-12-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_home_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MAIL', models.CharField(blank=True, max_length=300, verbose_name='mail')),
            ],
            options={
                'verbose_name': 'mail',
                'verbose_name_plural': 'Sub',
            },
        ),
    ]
